# Generated by Django 5.2.1 on 2025-05-26 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Brewing Date')),
                ('temperature', models.IntegerField(help_text='Temperature in Fahrenheit')),
                ('steeping_time', models.CharField(max_length=20)),
                ('amount', models.IntegerField(help_text='Amount in grams')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.tea')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
