# Generated by Django 5.2.1 on 2025-05-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_brewing'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewing',
            name='water_amount',
            field=models.IntegerField(default=280, help_text='Water amount in ml'),
            preserve_default=False,
        ),
    ]
