# Generated by Django 5.2.1 on 2025-05-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_brewing_water_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('teapot', 'Teapot'), ('gaiwan', 'Gaiwan'), ('cup', 'Tea Cup'), ('infuser', 'Tea Infuser'), ('dripper', 'Tea Dripper'), ('kettle', 'Kettle'), ('tray', 'Tea Tray')], max_length=20)),
                ('material', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(blank=True, help_text='Capacity in ml', null=True)),
                ('teas', models.ManyToManyField(blank=True, related_name='teaware', to='my_app.tea')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
